export type PopularCity = {
  city: string;
  slug?: string;
};

/** Five largest cities per US state and Canadian province (by population). */
export const POPULAR_CITIES_BY_REGION: Record<string, PopularCity[]> = {
  AL: [
    { city: "Birmingham", slug: "birmingham-alabama" },
    { city: "Huntsville" },
    { city: "Mobile" },
    { city: "Montgomery" },
    { city: "Tuscaloosa" },
  ],
  AK: [{ city: "Anchorage" }, { city: "Fairbanks" }, { city: "Juneau" }, { city: "Wasilla" }, { city: "Sitka" }],
  AZ: [
    { city: "Phoenix", slug: "phoenix-arizona" },
    { city: "Tucson" },
    { city: "Mesa" },
    { city: "Chandler" },
    { city: "Gilbert" },
  ],
  AR: [
    { city: "Little Rock" },
    { city: "Fayetteville" },
    { city: "Fort Smith" },
    { city: "Springdale" },
    { city: "Jonesboro" },
  ],
  CA: [
    { city: "Los Angeles", slug: "los-angeles-california" },
    { city: "San Diego", slug: "san-diego-california" },
    { city: "San Jose" },
    { city: "San Francisco", slug: "san-francisco-california" },
    { city: "Fresno" },
  ],
  CO: [
    { city: "Denver", slug: "denver-colorado" },
    { city: "Colorado Springs" },
    { city: "Aurora" },
    { city: "Fort Collins" },
    { city: "Lakewood" },
  ],
  CT: [
    { city: "Bridgeport" },
    { city: "New Haven" },
    { city: "Stamford" },
    { city: "Hartford" },
    { city: "Waterbury" },
  ],
  DE: [{ city: "Wilmington" }, { city: "Dover" }, { city: "Newark" }, { city: "Middletown" }, { city: "Smyrna" }],
  FL: [
    { city: "Jacksonville" },
    { city: "Miami", slug: "miami-florida" },
    { city: "Tampa", slug: "tampa-florida" },
    { city: "Orlando", slug: "orlando-florida" },
    { city: "St. Petersburg" },
  ],
  GA: [
    { city: "Atlanta", slug: "atlanta-georgia" },
    { city: "Augusta" },
    { city: "Columbus" },
    { city: "Macon" },
    { city: "Savannah" },
  ],
  HI: [{ city: "Honolulu" }, { city: "Pearl City" }, { city: "Hilo" }, { city: "Kailua" }, { city: "Waipahu" }],
  ID: [{ city: "Boise" }, { city: "Meridian" }, { city: "Nampa" }, { city: "Idaho Falls" }, { city: "Caldwell" }],
  IL: [
    { city: "Chicago", slug: "chicago-illinois" },
    { city: "Aurora" },
    { city: "Naperville" },
    { city: "Joliet" },
    { city: "Rockford" },
  ],
  IN: [
    { city: "Indianapolis", slug: "indianapolis-indiana" },
    { city: "Fort Wayne" },
    { city: "Evansville" },
    { city: "South Bend" },
    { city: "Carmel" },
  ],
  IA: [
    { city: "Des Moines" },
    { city: "Cedar Rapids" },
    { city: "Davenport" },
    { city: "Sioux City" },
    { city: "Iowa City" },
  ],
  KS: [
    { city: "Wichita" },
    { city: "Overland Park" },
    { city: "Kansas City" },
    { city: "Olathe" },
    { city: "Topeka" },
  ],
  KY: [
    { city: "Louisville" },
    { city: "Lexington" },
    { city: "Bowling Green" },
    { city: "Owensboro" },
    { city: "Covington" },
  ],
  LA: [{ city: "New Orleans" }, { city: "Baton Rouge" }, { city: "Shreveport" }, { city: "Lafayette" }, { city: "Lake Charles" }],
  ME: [{ city: "Portland" }, { city: "Lewiston" }, { city: "Bangor" }, { city: "South Portland" }, { city: "Auburn" }],
  MD: [{ city: "Baltimore" }, { city: "Frederick" }, { city: "Rockville" }, { city: "Gaithersburg" }, { city: "Bowie" }],
  MA: [{ city: "Boston" }, { city: "Worcester" }, { city: "Springfield" }, { city: "Cambridge" }, { city: "Lowell" }],
  MI: [
    { city: "Detroit", slug: "detroit-michigan" },
    { city: "Grand Rapids" },
    { city: "Warren" },
    { city: "Sterling Heights" },
    { city: "Ann Arbor" },
  ],
  MN: [{ city: "Minneapolis" }, { city: "Saint Paul" }, { city: "Rochester" }, { city: "Duluth" }, { city: "Bloomington" }],
  MS: [{ city: "Jackson" }, { city: "Gulfport" }, { city: "Southaven" }, { city: "Hattiesburg" }, { city: "Biloxi" }],
  MO: [{ city: "Kansas City" }, { city: "St. Louis" }, { city: "Springfield" }, { city: "Columbia" }, { city: "Independence" }],
  MT: [{ city: "Billings" }, { city: "Missoula" }, { city: "Great Falls" }, { city: "Bozeman" }, { city: "Helena" }],
  NE: [{ city: "Omaha" }, { city: "Lincoln" }, { city: "Bellevue" }, { city: "Grand Island" }, { city: "Kearney" }],
  NV: [{ city: "Las Vegas" }, { city: "Henderson" }, { city: "Reno" }, { city: "North Las Vegas" }, { city: "Sparks" }],
  NH: [{ city: "Manchester" }, { city: "Nashua" }, { city: "Concord" }, { city: "Derry" }, { city: "Rochester" }],
  NJ: [{ city: "Newark" }, { city: "Jersey City" }, { city: "Paterson" }, { city: "Elizabeth" }, { city: "Trenton" }],
  NM: [{ city: "Albuquerque" }, { city: "Las Cruces" }, { city: "Rio Rancho" }, { city: "Santa Fe" }, { city: "Roswell" }],
  NY: [
    { city: "New York City", slug: "new-york-city-new-york" },
    { city: "Buffalo" },
    { city: "Rochester" },
    { city: "Yonkers" },
    { city: "Syracuse" },
  ],
  NC: [
    { city: "Charlotte", slug: "charlotte-north-carolina" },
    { city: "Raleigh" },
    { city: "Greensboro" },
    { city: "Durham" },
    { city: "Winston-Salem" },
  ],
  ND: [{ city: "Fargo" }, { city: "Bismarck" }, { city: "Grand Forks" }, { city: "Minot" }, { city: "West Fargo" }],
  OH: [
    { city: "Columbus", slug: "columbus-ohio" },
    { city: "Cleveland", slug: "cleveland-ohio" },
    { city: "Cincinnati", slug: "cincinnati-ohio" },
    { city: "Toledo" },
    { city: "Akron" },
  ],
  OK: [{ city: "Oklahoma City" }, { city: "Tulsa" }, { city: "Norman" }, { city: "Broken Arrow" }, { city: "Edmond" }],
  OR: [{ city: "Portland" }, { city: "Salem" }, { city: "Eugene" }, { city: "Gresham" }, { city: "Hillsboro" }],
  PA: [
    { city: "Philadelphia", slug: "philadelphia-pennsylvania" },
    { city: "Pittsburgh", slug: "pittsburgh-pennsylvania" },
    { city: "Allentown" },
    { city: "Reading" },
    { city: "Erie" },
  ],
  RI: [{ city: "Providence" }, { city: "Warwick" }, { city: "Cranston" }, { city: "Pawtucket" }, { city: "East Providence" }],
  SC: [{ city: "Charleston" }, { city: "Columbia" }, { city: "North Charleston" }, { city: "Mount Pleasant" }, { city: "Greenville" }],
  SD: [{ city: "Sioux Falls" }, { city: "Rapid City" }, { city: "Aberdeen" }, { city: "Brookings" }, { city: "Watertown" }],
  TN: [
    { city: "Nashville", slug: "nashville-tennessee" },
    { city: "Memphis" },
    { city: "Knoxville" },
    { city: "Chattanooga" },
    { city: "Clarksville" },
  ],
  TX: [
    { city: "Houston", slug: "houston-texas" },
    { city: "San Antonio" },
    { city: "Dallas", slug: "dallas-texas" },
    { city: "Austin", slug: "austin-texas" },
    { city: "Fort Worth" },
  ],
  UT: [{ city: "Salt Lake City" }, { city: "West Valley City" }, { city: "West Jordan" }, { city: "Provo" }, { city: "St. George" }],
  VT: [{ city: "Burlington" }, { city: "Essex" }, { city: "South Burlington" }, { city: "Colchester" }, { city: "Montpelier" }],
  VA: [
    { city: "Virginia Beach" },
    { city: "Norfolk" },
    { city: "Chesapeake" },
    { city: "Richmond" },
    { city: "Newport News" },
  ],
  WA: [{ city: "Seattle" }, { city: "Spokane" }, { city: "Tacoma" }, { city: "Vancouver" }, { city: "Bellevue" }],
  WV: [{ city: "Charleston" }, { city: "Huntington" }, { city: "Morgantown" }, { city: "Parkersburg" }, { city: "Wheeling" }],
  WI: [{ city: "Milwaukee" }, { city: "Madison" }, { city: "Green Bay" }, { city: "Kenosha" }, { city: "Racine" }],
  WY: [{ city: "Cheyenne" }, { city: "Casper" }, { city: "Laramie" }, { city: "Gillette" }, { city: "Rock Springs" }],
  // Canadian provinces
  ON: [
    { city: "Toronto", slug: "toronto-ontario" },
    { city: "Mississauga" },
    { city: "Brampton" },
    { city: "Ottawa" },
    { city: "Hamilton" },
  ],
  QC: [{ city: "Montreal" }, { city: "Quebec City" }, { city: "Laval" }, { city: "Gatineau" }, { city: "Longueuil" }],
  BC: [{ city: "Vancouver" }, { city: "Surrey" }, { city: "Burnaby" }, { city: "Richmond" }, { city: "Kelowna" }],
  AB: [{ city: "Calgary" }, { city: "Edmonton" }, { city: "Red Deer" }, { city: "Lethbridge" }, { city: "St. Albert" }],
  MB: [{ city: "Winnipeg" }, { city: "Brandon" }, { city: "Steinbach" }, { city: "Thompson" }, { city: "Portage la Prairie" }],
  SK: [{ city: "Saskatoon" }, { city: "Regina" }, { city: "Prince Albert" }, { city: "Moose Jaw" }, { city: "Swift Current" }],
  NS: [{ city: "Halifax" }, { city: "Dartmouth" }, { city: "Sydney" }, { city: "Truro" }, { city: "New Glasgow" }],
  NB: [{ city: "Moncton" }, { city: "Saint John" }, { city: "Fredericton" }, { city: "Dieppe" }, { city: "Miramichi" }],
  NL: [{ city: "St. John's" }, { city: "Mount Pearl" }, { city: "Corner Brook" }, { city: "Grand Falls-Windsor" }, { city: "Gander" }],
  PE: [{ city: "Charlottetown" }, { city: "Summerside" }, { city: "Stratford" }, { city: "Cornwall" }, { city: "Montague" }],
  NT: [{ city: "Yellowknife" }, { city: "Hay River" }, { city: "Inuvik" }, { city: "Fort Smith" }, { city: "Norman Wells" }],
  YT: [{ city: "Whitehorse" }, { city: "Dawson City" }, { city: "Watson Lake" }, { city: "Haines Junction" }, { city: "Carmacks" }],
  NU: [{ city: "Iqaluit" }, { city: "Rankin Inlet" }, { city: "Arviat" }, { city: "Baker Lake" }, { city: "Cambridge Bay" }],
};
