import type { EventWithHomes } from "@/types/database";

const sampleInviteFields = {
  invite_token: null,
  invite_status: "active" as const,
  approval_status: "approved" as const,
  seller_email: null,
  seller_phone: null,
  submitted_at: null,
  approved_at: new Date().toISOString(),
  approved_by: null,
  last_edited_at: null,
};

export const SAMPLE_EVENT: EventWithHomes = {
  id: "sample",
  organizer_id: "sample",
  title: "Maplewood Community Garage Sale",
  slug: "maplewood-community-garage-sale",
  description:
    "Join us for the annual Maplewood neighborhood garage sale! Fifteen homes participating with furniture, toys, tools, clothing, and more. Grab a coffee and stroll the neighborhood — early birds welcome!",
  event_date: "2026-06-08",
  start_time: "08:00:00",
  end_time: "15:00:00",
  city: "Maplewood",
  region: "NJ",
  country: "US",
  main_address: "45 Maple Avenue, Maplewood, NJ 07040",
  latitude: 40.7312,
  longitude: -74.2734,
  status: "published",
  tier: "neighborhood",
  max_homes: 20,
  is_featured: true,
  payment_status: "paid",
  stripe_session_id: null,
  banner_image_url: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  homes: [
    {
      id: "h1",
      event_id: "sample",
      seller_name: "The Johnson Family",
      address: "12 Oak Street, Maplewood, NJ 07040",
      latitude: 40.7321,
      longitude: -74.2741,
      description: "Moving sale — lots of furniture and kitchen items!",
      categories: ["Furniture", "Kitchen", "Home Decor"],
      featured_items: ["Dining table set", "KitchenAid mixer", "Area rugs"],
      opening_time: "08:00:00",
      closing_time: "14:00:00",
      notes: "Cash preferred. Early birds welcome!",
      sort_order: 0,
      ...sampleInviteFields,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      home_photos: [],
    },
    {
      id: "h2",
      event_id: "sample",
      seller_name: "Sarah M.",
      address: "28 Birch Lane, Maplewood, NJ 07040",
      latitude: 40.7308,
      longitude: -74.272,
      description: "Kids clothes, toys, and baby gear.",
      categories: ["Baby & Kids", "Clothing", "Toys"],
      featured_items: ["LEGO sets", "Stroller", "Winter coats (size 4-6)"],
      opening_time: "08:00:00",
      closing_time: "15:00:00",
      notes: null,
      sort_order: 1,
      ...sampleInviteFields,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      home_photos: [],
    },
    {
      id: "h3",
      event_id: "sample",
      seller_name: "Mike's Tool Shed",
      address: "55 Pine Court, Maplewood, NJ 07040",
      latitude: 40.7315,
      longitude: -74.2755,
      description: "Hand tools, power tools, and workshop equipment.",
      categories: ["Tools", "Garden", "Sports"],
      featured_items: ["Circular saw", "Garden tools", "Golf clubs"],
      opening_time: "07:30:00",
      closing_time: "13:00:00",
      notes: "Multi-family sale with the Garcias next door!",
      sort_order: 2,
      ...sampleInviteFields,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      home_photos: [],
    },
    {
      id: "h4",
      event_id: "sample",
      seller_name: "Books & Treasures",
      address: "101 Elm Avenue, Maplewood, NJ 07040",
      latitude: 40.7299,
      longitude: -74.2715,
      description: "Estate sale — antiques, books, and collectibles.",
      categories: ["Books", "Antiques", "Collectibles", "Estate Sale"],
      featured_items: ["Vintage vinyl records", "First edition books", "Crystal vases"],
      opening_time: "09:00:00",
      closing_time: "15:00:00",
      notes: "Estate sale — everything must go!",
      sort_order: 3,
      ...sampleInviteFields,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      home_photos: [],
    },
    {
      id: "h5",
      event_id: "sample",
      seller_name: "Free Stuff Corner",
      address: "77 Cedar Road, Maplewood, NJ 07040",
      latitude: 40.733,
      longitude: -74.273,
      description: "Free items on the curb plus low-priced electronics.",
      categories: ["Free Items", "Electronics"],
      featured_items: ["Old monitors (free)", "Cables and adapters", "Desk lamp"],
      opening_time: "08:00:00",
      closing_time: "12:00:00",
      notes: "Free items on the curb — first come first served!",
      sort_order: 4,
      ...sampleInviteFields,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      home_photos: [],
    },
  ],
};

export const SAMPLE_EVENT_SLUG = SAMPLE_EVENT.slug;
